version: "3"

services:
  backend: 
    build: ./backend/
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  frontend:
    image: frontend-pokemon
    build: ./frontend/
    command: npm run dev
    ports:
      - "80:5173"
  postgres:
    image: postgres
    container_name: postgres-database
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: article
    volumes:
      - ./backend/src/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
